# Generated by Django 6.0.4 on 2026-04-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(default='Global Courier Internal', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='comment',
            field=models.TextField(blank=True, help_text='Internal staff comments', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.CharField(default='General Logistics', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_mode',
            field=models.CharField(choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight'), ('ROAD', 'Road Transport'), ('RAIL', 'Rail Transport')], default='AIR', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H (cm)', max_length=100, null=True)),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipments.shipment')),
            ],
        ),
    ]
