# Generated by Django 6.0.4 on 2026-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_carrier_shipment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='current_country',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('DEU', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('CHN', 'China'), ('JPN', 'Japan'), ('IND', 'India'), ('AUS', 'Australia'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('ZAF', 'South Africa'), ('NGA', 'Nigeria'), ('ARE', 'United Arab Emirates'), ('SAU', 'Saudi Arabia'), ('QAT', 'Qatar'), ('TUR', 'Turkey'), ('RUS', 'Russia'), ('KOR', 'South Korea'), ('SGP', 'Singapore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination_country',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('DEU', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('CHN', 'China'), ('JPN', 'Japan'), ('IND', 'India'), ('AUS', 'Australia'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('ZAF', 'South Africa'), ('NGA', 'Nigeria'), ('ARE', 'United Arab Emirates'), ('SAU', 'Saudi Arabia'), ('QAT', 'Qatar'), ('TUR', 'Turkey'), ('RUS', 'Russia'), ('KOR', 'South Korea'), ('SGP', 'Singapore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin_country',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('DEU', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('CHN', 'China'), ('JPN', 'Japan'), ('IND', 'India'), ('AUS', 'Australia'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('ZAF', 'South Africa'), ('NGA', 'Nigeria'), ('ARE', 'United Arab Emirates'), ('SAU', 'Saudi Arabia'), ('QAT', 'Qatar'), ('TUR', 'Turkey'), ('RUS', 'Russia'), ('KOR', 'South Korea'), ('SGP', 'Singapore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shipmenthistory',
            name='location_country',
            field=models.CharField(choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('DEU', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('ESP', 'Spain'), ('CHN', 'China'), ('JPN', 'Japan'), ('IND', 'India'), ('AUS', 'Australia'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('ZAF', 'South Africa'), ('NGA', 'Nigeria'), ('ARE', 'United Arab Emirates'), ('SAU', 'Saudi Arabia'), ('QAT', 'Qatar'), ('TUR', 'Turkey'), ('RUS', 'Russia'), ('KOR', 'South Korea'), ('SGP', 'Singapore')], max_length=100),
        ),
    ]
