# Generated by Django 6.0.4 on 2026-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_alter_shipment_current_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(choices=[('FLEET_DIRECT', 'Fleet Direct Internal'), ('DHL', 'DHL Express'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('ARAMEX', 'Aramex'), ('TNT', 'TNT'), ('USPS', 'USPS'), ('ROYAL_MAIL', 'Royal Mail'), ('CANADA_POST', 'Canada Post'), ('AUSTRALIA_POST', 'Australia Post'), ('SF_EXPRESS', 'SF Express'), ('EMS', 'EMS')], default='FLEET_DIRECT', max_length=100),
        ),
    ]
